### ISSUE TITLE
Fetch.py not running in crontab

### ISSUE THREAD

**Issue by k9barry** [greencoder/noaa-alerts-pushover#1]
I have installed your script and have it working well when I use the command line to call fetch.py

`python /home/jc/noaa/fetch.py`

My problem is when I try to use `crontab -U jc -e` and try to call fetch.py with 

`*/2 * * * * python /home/jc/noaa/fetch.py --purge`  Nothing is sent.

I am receiving the errors below but I do not know where to start to correct them. Any help you could provide in pointing me in the right direction would be greatly appreciated.

> Subject: Cron <jc@server> /usr/bin/python /home/jc/noaa/fetch.py --purge
> MIME-Version: 1.0
> Content-Type: text/plain; charset=UTF-8
> Content-Transfer-Encoding: 8bit
> X-Cron-Env: <SHELL=/bin/sh>
> X-Cron-Env: <HOME=/home/jc>
> X-Cron-Env: <PATH=/usr/bin:/bin>
> X-Cron-Env: <LOGNAME=jc>
> 
> Traceback (most recent call last):
>   File "/home/jc/noaa/fetch.py", line 262, in <module>
>     template = template_env.get_template(template_file)
>   File "/home/jc/.local/lib/python2.7/site-packages/jinja2/environment.py", line 812, in get_template
>     return self._load_template(name, self.make_globals(globals))
>   File "/home/jc/.local/lib/python2.7/site-packages/jinja2/environment.py", line 774, in _load_template
>     cache_key = self.loader.get_source(self, name)[1]
>   File "/home/jc/.local/lib/python2.7/site-packages/jinja2/loaders.py", line 187, in get_source
>     raise TemplateNotFound(template)
> jinja2.exceptions.TemplateNotFound: detail.html

**Comment by k9barry** [comment]
Reminder :  This runs perfect when I use a command line - these errors only occur when I try to run this in crontab as user jc:

So I have been digging a little further and found out the errors listed above go away when I replace:
`template_loader = jinja2.FileSystemLoader('./templates')`
with
`template_loader = jinja2.FileSystemLoader('/home/jc/noaa/templates')`

That's all and good but now I get these errors:
`Traceback (most recent call last):
  File "/home/jc/noaa/fetch.py", line 312, in <module>
    count = Alert.delete().where(Alert.expires_utc_ts < ago_ts).execute()
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 2884, in execute
    return self.database.rows_affected(self._execute())
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 2371, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3073, in execute_sql
    self.commit()
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 2922, in __exit__
    reraise(new_type, new_type(*exc_value.args), traceback)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3065, in execute_sql
    cursor.execute(sql, params or ())
peewee.OperationalError: no such table: alert

Still digging into these but if anyone has an idea......`

**Comment by k9barry** [comment]
I have verified that I ran `python models.py`  which created the alerts.db file and the models.pyc file.

Also, after running python fetch.py from the command line the alerts.db file gets populated.

**Comment by k9barry** [comment]
Ok tracked down the last remaining problem.
In the models.py file I had to use the full root path to the alerts.db file to get this to work with crontab.

I hope this helps anyone one else who goes down this road.
